name: flutter_base_2024
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.4.0
  # Hive (local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.7.0
  pull_to_refresh_flutter3: ^2.0.1
  url_launcher: ^6.1.10
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.7+1
  image_cropping: ^0.0.13
  webview_flutter: ^4.0.7
  photo_view: ^0.14.0
  qr_flutter: ^4.0.0
  intl: ^0.18.0
  cached_network_image: ^3.2.1
  animate_do: ^2.1.0
  flutter_html: ^3.0.0-alpha.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets: