name: flutter_base_2024
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.4.0
  # Hive (local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.7.0
  pull_to_refresh_flutter3: ^2.0.1
  url_launcher: ^6.1.10
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.7+1
  image_cropping: ^0.0.13
  photo_view: ^0.14.0
  qr_flutter: ^4.0.0
  intl: ^0.18.0
  cached_network_image: ^3.2.1
  animate_do: ^2.1.0
  # webview_flutter: ^4.0.7
  # flutter_html: ^3.0.0-alpha.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Lato/Lato-Black.ttf
          weight: 900
    - family: HonorSansCN
      fonts:
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/HONORSansCN/HONORSansCN-Heavy.ttf
          weight: 900
